---
# tasks file for cmp_ip_configure

- block:
  - name: Decommission IP
    ansible.builtin.debug:
      var: inventory_hostname
  rescue:
  - name: Update Inventory
    ansible.controller.host:
      name: "{{ inventory_hostname }}"
      inventory: Configuration Items
      state: present
      # We need a merge mechanism here...
      variables: "{{ hostvars[inventory_hostname] }}"
    delegate_to: localhost

  - name: Failing after rescue
    ansible.builtin.fail:
      msg: "{{ ansible_failed_result }}"