- name: Build VM Component
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Deploy VM
    jritter.products.configuration_item:
      name: myvm
      type: vm
      state: present
      variables:
        vm_ram_mb: 4096
        