- name: Build Gitlab Component
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Deploy Gitlab
    jritter.products.configuration_item:
      name: mygitlab
      type: gitlab
      state: present
      variables:
        name: "Hello Gitlab!"

