- name: Configure AAP
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Install Build IP Component Template
      ansible.controller.job_template:
        name: Build IP Component
        job_type: "run"
        organization: "Default"
        inventory: "Localhost"
        project: "Products"
        playbook: "build_ip.yml"
        credentials:
          - "AAP"
        ask_variables_on_launch: true
        state: "present"

    - name: Install Build VM Component Template
      ansible.controller.job_template:
        name: Build VM Component
        job_type: "run"
        organization: "Default"
        inventory: "Localhost"
        project: "Products"
        playbook: "build_vm.yml"
        credentials:
          - "AAP"
        ask_variables_on_launch: true
        state: "present"

    - name: Install Build Postgres Component Template
      ansible.controller.job_template:
        name: Build Postgres Component
        job_type: "run"
        organization: "Default"
        inventory: "Localhost"
        project: "Products"
        playbook: "build_postgres.yml"
        credentials:
          - "AAP"
        ask_variables_on_launch: true
        state: "present"

    - name: Install Build GitLab Component Template
      ansible.controller.job_template:
        name: Build GitLab Component
        job_type: "run"
        organization: "Default"
        inventory: "Localhost"
        project: "Products"
        playbook: "build_gitlab.yml"
        credentials:
          - "AAP"
        ask_variables_on_launch: true
        state: "present"
