- name: Destroy Postgres Component
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Destroy Postgres
    jritter.products.configuration_item:
      name: mypostgres
      type: postgres
      state: absent
        